apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: app
spec:
  selector:
    app: data-service
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: ClusterIP
